In [1]:
!pip install scikit-learn

  Using cached scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl.metadata (13 kB)
  Using cached numpy-2.1.2-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
  Using cached scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl (11.0 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached numpy-2.1.2-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
Using cached scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl (23.1 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
documents = [
"Hello world",
"Machine learning is fascinating",
"Hello from the other side"
]

In [4]:
vectorizer = CountVectorizer()

In [5]:
bow_model = vectorizer.fit_transform(documents)

In [6]:
print("Vocabulary: ", vectorizer.get_feature_names_out())
print("Bag-of-Words Matrix:\n", bow_model.toarray())

Vocabulary:  ['fascinating' 'from' 'hello' 'is' 'learning' 'machine' 'other' 'side'
 'the' 'world']
Bag-of-Words Matrix:
 [[0 0 1 0 0 0 0 0 0 1]
 [1 0 0 1 1 1 0 0 0 0]
 [0 1 1 0 0 0 1 1 1 0]]


In [ ]:
!pip install scikit-learn

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
documents = ["Data science is about the extraction of knowledge from data.","Machine learning is a subset of data science.","Statistics is important for data analysis."]

In [9]:
tfidf_vectorizer = TfidfVectorizer()

In [11]:
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

In [12]:
print("Vocabulary: ", tfidf_vectorizer.get_feature_names_out())
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())

Vocabulary:  ['about' 'analysis' 'data' 'extraction' 'for' 'from' 'important' 'is'
 'knowledge' 'learning' 'machine' 'of' 'science' 'statistics' 'subset'
 'the']
TF-IDF Matrix:
 [[0.35576296 0.         0.42023867 0.35576296 0.         0.35576296
  0.         0.21011934 0.35576296 0.         0.         0.2705669
  0.2705669  0.         0.         0.35576296]
 [0.         0.         0.26806191 0.         0.         0.
  0.         0.26806191 0.         0.45386827 0.45386827 0.34517852
  0.34517852 0.         0.45386827 0.        ]
 [0.         0.46138073 0.27249889 0.         0.46138073 0.
  0.46138073 0.27249889 0.         0.         0.         0.
  0.         0.46138073 0.         0.        ]]


In [13]:
!pip install nltk

  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached regex-2024.9.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Using cached regex-2024.9.11-cp311-cp311-macosx_11_0_arm64.whl (284 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached tqdm-4.66.5-py3-none-any.whl (78 kB)


In [14]:
import nltk
from nltk.util import ngrams
from nltk import FreqDist

In [15]:
text = "The quick brown fox jumps over the lazy dog. The quick brown fox is very friendly."
tokens = nltk.word_tokenize(text.lower())

In [16]:
trigrams = list(ngrams(tokens, 3))

In [17]:
freq_dist = FreqDist(trigrams)

In [18]:
print("Most common trigrams:", freq_dist.most_common(5))

Most common trigrams: [(('the', 'quick', 'brown'), 2), (('quick', 'brown', 'fox'), 2), (('brown', 'fox', 'jumps'), 1), (('fox', 'jumps', 'over'), 1), (('jumps', 'over', 'the'), 1)]


In [19]:
!pip install gensim
!pip install nltk

  Using cached gensim-4.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.1 kB)
  Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (114 kB)
  Using cached scipy-1.13.1-cp311-cp311-macosx_12_0_arm64.whl.metadata (60 kB)
  Using cached smart_open-7.0.5-py3-none-any.whl.metadata (24 kB)
  Using cached wrapt-1.16.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.6 kB)
Using cached gensim-4.3.3-cp311-cp311-macosx_11_0_arm64.whl (24.0 MB)
Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Using cached scipy-1.13.1-cp311-cp311-macosx_12_0_arm64.whl (30.3 MB)
Using cached smart_open-7.0.5-py3-none-any.whl (61 kB)
Using cached wrapt-1.16.0-cp311-cp311-macosx_11_0_arm64.whl (38 kB)
  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached regex-2024.9.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
  Using cached

In [1]:
from gensim.models import Word2Vec
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /Users/vincenzo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
text = "Gensim is a free Python library designed to automatically extract semantic topics from documents, as efficiently (computer-wise) and painlessly (developer-wise) as possible. Each word extracted is associated with a semantically similar word and related with the key word with a score."

In [3]:
tokens = word_tokenize(text.lower())

In [4]:
model = Word2Vec([tokens], vector_size=100, window=5, min_count=1, workers=4)

In [5]:
vector = model.wv['semantic']

In [6]:
similar_words = model.wv.most_similar('semantic', topn=5)
print("Vector for semantic", vector)
print("Similar Words to semantic", similar_words)

Vector for semantic [-7.2039370e-03  4.2333868e-03  2.1752534e-03  7.4414364e-03
 -4.8977309e-03 -4.5761457e-03 -6.0947640e-03  3.3138609e-03
 -4.4987719e-03  8.5021555e-03 -4.2823050e-03 -9.1200555e-03
 -4.8112506e-03  6.4195883e-03 -6.3683414e-03 -5.2705724e-03
 -7.2916839e-03  6.0137836e-03  3.3499887e-03  2.8379695e-03
 -3.1343552e-03  6.0368581e-03 -6.1400961e-03 -1.9771315e-03
 -5.9908722e-03 -9.8796573e-04 -2.0235940e-03  8.4915459e-03
  7.5735741e-05 -8.5635278e-03 -5.4317806e-03 -6.8827448e-03
  2.6955521e-03  9.4368514e-03 -5.8200913e-03  8.2803443e-03
  8.5457237e-03 -7.0734336e-03 -8.8868784e-03  9.4809709e-03
  8.3872639e-03 -4.6972502e-03 -6.7255059e-03  7.8438474e-03
  3.7747303e-03  8.0964621e-03 -7.5768516e-03 -9.5237698e-03
  1.5801457e-03 -9.8101227e-03 -4.8847818e-03 -3.4647249e-03
  9.6243452e-03  8.6196708e-03 -2.8423336e-03  5.8348249e-03
  8.2500027e-03 -2.2536295e-03  9.5423684e-03  7.1657347e-03
  2.0430537e-03 -3.8590822e-03 -5.0711813e-03 -3.0517727e-03
  7.

In [1]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /Users/vincenzo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
text_corpus = [
"Deep learning achieves great success in various AI fields.",
"Transformers is a deep neural network that is fundamental in field of generative AI",
"The representation of words as vectors facilitates understanding."
]
tagged_data = [TaggedDocument(words=word_tokenize(_d.lower()), tags=[str(i)]) for i, _d in enumerate(text_corpus)]

In [3]:
model = Doc2Vec(vector_size=100, window=2, min_count=1, workers=4, epochs=40)
model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)

In [4]:
sentence_vectors = [model.dv[str(i)] for i in range(len(text_corpus))]

In [5]:
similarity = model.dv.n_similarity(['0'], ['1'])

In [6]:
print('Sentence Vectors', sentence_vectors)
print("Similarity between first two sentences:", similarity)

Sentence Vectors [array([-6.08640723e-03, -6.41583651e-03, -1.02106286e-02,  9.02161375e-03,
        3.79280420e-03, -3.16040241e-05, -9.94128920e-03, -5.01294946e-03,
       -1.01299081e-02,  2.12175795e-03,  2.69107590e-03,  4.72153723e-03,
       -4.67562536e-03, -3.64509481e-03, -2.54761940e-03, -9.16371681e-03,
        2.25732056e-03,  9.62740928e-03, -9.99422744e-03, -3.79347824e-03,
       -3.83211044e-03,  2.71871756e-03, -5.71148936e-03,  3.07458011e-03,
        5.40895853e-03, -8.23027827e-03, -9.26456042e-03, -1.03328852e-02,
        5.17852511e-03, -9.55102593e-03,  6.40852191e-03,  6.84440508e-03,
       -6.60783565e-03, -4.88108350e-03, -1.68252771e-03,  1.96183124e-03,
       -1.67012552e-03, -8.94778688e-03, -4.17830376e-03,  1.41245406e-03,
       -1.33543555e-03, -7.35586556e-03,  4.82200179e-03, -9.18009318e-03,
        2.62762373e-03, -4.87691583e-03,  6.62836537e-04, -1.84217317e-03,
        5.49838226e-03, -8.85788817e-03, -2.54443241e-03, -1.54579873e-04,
       

In [1]:
!pip install transformers
!pip install torch

  Using cached transformers-4.45.2-py3-none-any.whl.metadata (44 kB)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached huggingface_hub-0.25.2-py3-none-any.whl.metadata (13 kB)
  Using cached numpy-2.1.2-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
  Using cached PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.1 kB)
  Using cached regex-2024.9.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
  Using cached safetensors-0.4.5-cp311-cp311-macosx_11_0_arm64.whl.metadata (3.8 kB)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
  Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
  Using cached charset_normalizer-3.4.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (34 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.

In [1]:
from transformers import BertTokenizer, BertForSequenceClassification
from torch.nn.functional import softmax
import torch

/Users/vincenzo/Desktop/Libro/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=2)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [3]:
text = "BERT revolutionizes natural language processing."
encoded_input = tokenizer(text, return_tensors='pt')

In [5]:
print(encoded_input)

{'input_ids': tensor([[  101, 14324,  4329, 10057,  3019,  2653,  6364,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [7]:
print(encoded_input['input_ids'].shape)

torch.Size([1, 9])


In [8]:
print(encoded_input.keys())
print(encoded_input['input_ids'])
print(encoded_input['attention_mask'])

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
tensor([[  101, 14324,  4329, 10057,  3019,  2653,  6364,  1012,   102]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [ ]:
## errore pagina 14

In [12]:
output = model(encoded_input['input_ids'])

In [13]:
predictions = softmax(output.logits, dim=-1)

In [15]:
## corretto
output = model(
    input_ids=encoded_input['input_ids'],
    attention_mask=encoded_input['attention_mask'],
    token_type_ids = encoded_input['token_type_ids']
)
predictions = softmax(output.logits, dim=-1)

In [16]:
predicted_class = torch.argmax(predictions).item()
print("Predicted class:", predicted_class)

Predicted class: 0


In [1]:
!pip install spacy
!pip install nltk
!python -m spacy download en_core_web_sm

  Using cached spacy-3.8.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (27 kB)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
  Using cached murmurhash-1.0.10-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.0 kB)
  Using cached cymem-2.0.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.4 kB)
  Using cached preshed-3.0.9-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.2 kB)
  Using cached thinc-8.3.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (15 kB)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
  Using cached srsly-2.4.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (20 kB)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
  Using cached weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
  Using cached typer-0.12.5-py3-none-any.whl.metadata (15 kB)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB

In [2]:
import spacy
from nltk.tree import Tree

In [3]:
nlp = spacy.load('en_core_web_sm')

In [4]:
text = "John gave a book to Mary."
doc = nlp(text)

In [5]:
def get_syntax_tree(doc):
    def to_nltk_tree(node):
        if node.n_lefts + node.n_rights > 0:
            return Tree(node.orth_, [to_nltk_tree(child) for child in node.children])
        else:
            return node.orth_
    return [to_nltk_tree(sent.root) for sent in doc.sents]
syntax_tree = get_syntax_tree(doc)

In [6]:
def identify_roles(doc):
    roles = {}
    for token in doc:
        if token.dep_ == 'ROOT':
            predicate = token
            roles[predicate] = []
            for child in predicate.children:
                if child.dep_ in ('nsubj', 'dobj', 'iobj'):
                    roles[predicate].append((child, child.dep_))
    return roles

In [7]:
roles = identify_roles(doc)

In [8]:
for tree in syntax_tree:
    tree.pretty_print()
for predicate, arguments in roles.items():
    print(f"Predicate: {predicate}")
for arg, role in arguments:
    print(f" - Argument: {arg}, Role: {role}")

     gave          
  ____|_________    
 |    |   book  to 
 |    |    |    |   
John  .    a   Mary

Predicate: gave
 - Argument: John, Role: nsubj
 - Argument: book, Role: dobj


In [9]:
!pip install numpy
!pip install scikit-learn

  Using cached numpy-2.1.2-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
Using cached numpy-2.1.2-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
  Using cached scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl.metadata (13 kB)
  Using cached scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl (11.0 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl (23.1 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [1]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
words = ['apple', 'orange', 'banana', 'apple', 'orange']

In [3]:
word_dict = {word: idx for idx, word in enumerate(sorted(set(words)))}

In [4]:
def one_hot_encode(word):
    vector = np.zeros(len(word_dict))
    vector[word_dict[word]] = 1
    return vector
encoded_words = np.array([one_hot_encode(word) for word in words])

In [6]:
encoder = OneHotEncoder(sparse_output=False)
encoded_words_sklearn= encoder.fit_transform(np.array(words).reshape(-1, 1))

In [7]:
print("Custom One-Hot Encoding:\n", encoded_words)
print("Scikit-Learn One-Hot Encoding:\n", encoded_words_sklearn)

Custom One-Hot Encoding:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Scikit-Learn One-Hot Encoding:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [1]:
!pip install scikit-learn
!pip install nltk
!pip install gensim

  Using cached scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl.metadata (13 kB)
  Using cached numpy-2.1.2-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
  Using cached scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl (11.0 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached numpy-2.1.2-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
Using cached scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl (23.1 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
  Using cached regex-2024.9.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Using cached nltk-3.9.1-py3-none-any

In [2]:
from sklearn.cluster import KMeans
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec
import numpy as np

In [3]:
sentences = [
"Dogs are domestic animals.",
"Cats are pets.",
"Lions are wild animals.",
"Tigers are feline like cats"
]

In [4]:
tokens = [word_tokenize(sentence.lower()) for sentence in sentences]

In [5]:
model = Word2Vec(tokens, vector_size=100, window=5, min_count=1, workers=2)
word_vectors = model.wv

In [6]:
vectors = np.array([word_vectors[w] for w in word_vectors.index_to_key])

In [7]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(vectors)
word_clusters = {
word: kmeans.labels_[idx] for idx, word in
enumerate(word_vectors.index_to_key)
}
print(word_clusters)

{'are': 0, '.': 1, 'cats': 1, 'animals': 1, 'like': 0, 'feline': 1, 'tigers': 0, 'wild': 0, 'lions': 1, 'pets': 1, 'domestic': 0, 'dogs': 1}


In [ ]:
!pip install numpy scikit-learn

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
documents = ["The sky is blue.", "The sun is bright today.", "The sun in the sky is bright.", "We can see the shining sun, the bright sun."]

In [10]:
tfidf_vectorizer = TfidfVectorizer()

In [11]:
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

In [12]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [13]:
print(cosine_sim)

[[1.         0.28369456 0.52305744 0.13448867]
 [0.28369456 1.         0.56407998 0.41905905]
 [0.52305744 0.56407998 1.         0.43661098]
 [0.13448867 0.41905905 0.43661098 1.        ]]


In [14]:
print("Similarity between the first and third documents:", cosine_sim[0][2])

Similarity between the first and third documents: 0.523057438370366


In [1]:
!pip install spacy
!python -m spacy download en_core_web_sm

  Using cached spacy-3.8.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (27 kB)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
  Using cached murmurhash-1.0.10-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.0 kB)
  Using cached cymem-2.0.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.4 kB)
  Using cached preshed-3.0.9-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.2 kB)
  Using cached thinc-8.3.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (15 kB)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
  Using cached srsly-2.4.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (20 kB)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
  Using cached weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
  Using cached typer-0.12.5-py3-none-any.whl.metadata (15 kB)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB

In [2]:
import spacy
from spacy.matcher import Matcher

In [3]:
nlp = spacy.load('en_core_web_sm')

In [4]:
text = "Mark Zuckerberg founded Facebook in Menlo Park. Google was founded by Larry Page and Sergey Brin."
doc = nlp(text)

In [5]:
for ent in doc.ents:
    print(ent.text, ent.label_)

Mark Zuckerberg PERSON
Menlo Park GPE
Google ORG
Larry Page PERSON
Sergey Brin PERSON


In [6]:
matcher = Matcher(nlp.vocab)
pattern = [ 
    {'DEP': 'nsubj', 'ENT_TYPE': 'PERSON'},
    {'DEP': 'ROOT', 'LEMMA': 'found'},
    {'DEP': 'dobj', 'ENT_TYPE': 'ORG'}
]

In [7]:
matcher.add("founding_relationship", [pattern])
matches = matcher(doc)

In [8]:
for match_id, start, end in matches:
    span = doc[start:end]
    print("Relationship:", span.text)

In [9]:
relationships = []
for match_id, start, end in matches:
    span = doc[start:end]
    subject = span[0].text
    action = span[1].lemma_
    object = span[2].text
    relationships.append((subject, action, object))

In [10]:
for rel in relationships:
    print(f"Subject: {rel[0]}, Action: {rel[1]}, Object: {rel[2]}")